### ISSUE TITLE
Extraneous Comma after Remove Unused Imports

### ISSUE THREAD

**Issue by tydevries** [cefolger/needsmoredojo#63] opened 2013-06-25 18:33 UTC
Using IntelliJ IDEA 12.1.4 on JDK 1.7.0_10, extraneous comma left over after removing at least two unused imports when said imports are at the end of the declare clause.

To replicate:
1. Create a new module with at least three includes. Ensure that the last two are unused.
2. Remove unused imports.
3. Trailing comma left at end of module declaration (see attached).

![nmd_before](https://f.cloud.github.com/assets/4822633/704631/07142560-ddc5-11e2-8aa8-4ac3ce328b0f.png)
![nmd_after](https://f.cloud.github.com/assets/4822633/704630/0713e65e-ddc5-11e2-8707-87111f8a82c0.png)

**Comment by cefolger** [comment] 2013-06-25 19:17
Duplicate of #57 which should be fixed. Thanks for the screenshots showing the problem!

**Closed as completed by cefolger** 2013-06-25 19:17 UTC
Labels: bug, duplicate
